# Book configuration
# Learn more: https://jupyterbook.org/customize/config.html

title: Example Jupyter Book
author: Example Author
logo: logo.png

execute:
  execute_notebooks: off

repository:
  url: https://github.com/yourusername/yourrepo
  path_to_book: .
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
